import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,Check,ChevronRight,Group as GroupIcon,Copy,EyeOff,Focus,Info,Layers3,Palette,Pause,Pencil,Plus,RotateCcw,RotateCw,Search,Tag,Tags,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Input} from '@/components/ui/input';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {MAX_LAYERS,colorLayers,includes,isHex,loadGroups,newGroupId,resolveParts,saveGroups,stripes,type Group} from './groups';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const PALETTE=['#e0453a','#2f6fdf','#2fa86b','#e3a21a','#8a4fd8','#e0559b'];
type Chosen=Concept&{kind?:'selection'|'group';colors?:string[]};
interface Draft {id:string|null;name:string;parts:string[];colors:string[];children:string[]}
const LABELS_KEY='human-atlas.group-labels';
function HexInput({value,label,onChange}:{value:string;label:string;onChange:(hex:string)=>void}){
 const [text,setText]=useState(value);useEffect(()=>setText(value),[value]);
 return <Input className="hex-input" value={text} aria-label={label} spellCheck={false} maxLength={7} onChange={e=>{const v=e.target.value.trim();setText(v);const hex=v.startsWith('#')?v:`#${v}`;if(isHex(hex))onChange(hex.toLowerCase());}}/>;
}
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|'groups'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Chosen|null>(null);
 const [groups,setGroups]=useState<Group[]>(loadGroups),[draft,setDraft]=useState<Draft|null>(null),[confirmDelete,setConfirmDelete]=useState<string|null>(null);
 const [showLabels,setShowLabels]=useState(()=>{try{return (localStorage.getItem(LABELS_KEY)??localStorage.getItem('human-atlas.combine-labels'))!=='off';}catch{return true;}});
 const loaded=useRef(groups);useEffect(()=>{if(groups!==loaded.current)saveGroups(groups);},[groups]);
 useEffect(()=>{try{localStorage.setItem(LABELS_KEY,showLabels?'on':'off');}catch{/* Preference then lasts for this session. */}},[showLabels]);
 const layers=useMemo(()=>colorLayers(groups),[groups]);
 const labels=useMemo(()=>showLabels?groups.filter(c=>!c.tagHidden).map(c=>({id:c.id,name:c.name,colors:c.colors,parts:resolveParts(groups,c.id)})):[],[groups,showLabels]);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);setDraft(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const selectPieces=(ids:string[])=>{
  const next=[...new Set(ids)].filter(id=>parts.has(id)),one=next.length===1?parts.get(next[0]):undefined;
  setState(s=>({...s,selected:next,isolate:false,rotate:false}));
  setChosen(!next.length?null:one?{id:one.conceptId,name:one.name,elements:next}:{id:'selection',name:`${next.length} selected pieces`,elements:next,kind:'selection'});
  setDetails(next.length>0&&!draft);setPanel(null);
 };
 const choosePart=(id:string,additive=false)=>selectPieces(additive?(state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id]):[id]);
 const nextColor=PALETTE[groups.length%PALETTE.length];
 const piecesOf=(c:Group,list=groups)=>resolveParts(list,c.id).filter(id=>parts.has(id));
 const showGroup=(c:Group,list=groups)=>{const ids=piecesOf(c,list);setChosen({id:c.id,name:c.name,elements:ids,kind:'group',colors:c.colors});setState(s=>({...s,selected:ids,isolate:false,rotate:false}));setDetails(ids.length>0);setPanel(null);setDraft(null);};
 const startDraft=(next:Draft)=>{setDraft(next);setPanel(null);setDetails(false);setConfirmDelete(null);setState(s=>({...s,selected:next.parts.filter(id=>parts.has(id)),isolate:false,rotate:false}));};
 const editGroup=(c:Group)=>startDraft({id:c.id,name:c.name,parts:c.parts,colors:c.colors.length?c.colors:[nextColor],children:c.children??[]});
 const duplicateGroup=(c:Group)=>startDraft({id:null,name:`${c.name} copy`,parts:c.parts,colors:c.colors.length?c.colors:[nextColor],children:c.children??[]});
 const saveDraft=()=>{
  if(!draft)return;const name=draft.name.trim(),colors=[...new Set(draft.colors.filter(isHex).map(c=>c.toLowerCase()))];if(!name||(!draft.parts.length&&!draft.children.length)||!colors.length)return;
  const saved:Group={id:draft.id??newGroupId(),name,parts:[...new Set(draft.parts)],colors,children:[...new Set(draft.children)],hidden:groups.find(c=>c.id===draft.id)?.hidden,tagHidden:groups.find(c=>c.id===draft.id)?.tagHidden};
  const next=groups.some(c=>c.id===saved.id)?groups.map(c=>c.id===saved.id?saved:c):[...groups,saved];
  setGroups(next);setDraft(null);showGroup(saved,next);
 };
 const deleteGroup=(id:string)=>{setGroups(list=>list.filter(c=>c.id!==id).map(c=>c.children?.includes(id)?{...c,children:c.children.filter(x=>x!==id)}:c));setConfirmDelete(null);if(chosen?.id===id){setChosen(null);setDetails(false);setState(s=>({...s,selected:[],isolate:false}));}};
 const toggleGroupColors=(id:string)=>setGroups(list=>list.map(c=>c.id===id?{...c,hidden:!c.hidden}:c));
 const toggleGroupTag=(id:string)=>setGroups(list=>list.map(c=>c.id===id?{...c,tagHidden:!c.tagHidden}:c));
 const setDraftColor=(i:number,color:string)=>setDraft(d=>d&&{...d,colors:d.colors.map((c,k)=>k===i?color:c)});
 const pending=draft?state.selected.filter(id=>!draft.parts.includes(id)):[];
 const includable=draft?groups.filter(c=>c.id!==draft.id&&!(draft.id&&includes(groups,c.id,draft.id))):[];
 const toggleDraftChild=(id:string)=>setDraft(d=>d&&{...d,children:d.children.includes(id)?d.children.filter(x=>x!==id):[...d.children,id]});
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search'|'groups')=>{setDetails(false);setDraft(null);setConfirmDelete(null);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0,layers,labels}} onSelect={choosePart} onLabel={id=>{const c=groups.find(x=>x.id===id);if(c)showGroup(c);}} onBoxSelect={ids=>selectPieces([...state.selected,...ids])} onClear={()=>{setState(s=>({...s,selected:[],isolate:false}));setChosen(null);setDetails(false);}} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE ANATOMY</div><h1>Human Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className={panel==='groups'||draft?'active':''} onClick={()=>openPanel('groups')} aria-label="Show groups"><Tags size={18}/><span>Groups</span>{groups.length>0&&<b className="group-count">{groups.length}</b>}</Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setDraft(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  {panel==='groups'&&<section className="search-panel groups-panel glass" aria-label="Groups">
   <div className="panel-heading"><span>Groups</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close groups"><X size={18}/></Button></div>
   {groups.length?<ul className="group-list">{groups.map(c=><li key={c.id} className={`group-row ${c.hidden?'is-hidden':''} ${c.tagHidden?'tag-off':''}`}>
    <Button variant="ghost" className="group-name" title={`Select ${c.name}`} onClick={()=>showGroup(c)}><span className="group-swatch" style={{background:stripes(c.colors)}}/><span className="group-label">{c.name}</span><span className="small-number">{piecesOf(c).length}</span></Button>
    {confirmDelete===c.id?<><Button variant="ghost" className="group-confirm" onClick={()=>deleteGroup(c.id)}>Delete</Button><Button variant="ghost" className="group-icon" aria-label={`Keep ${c.name}`} onClick={()=>setConfirmDelete(null)}><X size={15}/></Button></>:<>
     <Button variant="ghost" className={`group-icon group-toggle-icon ${c.hidden?'is-off':''}`} aria-pressed={!c.hidden} aria-label={c.hidden?`Show colors of ${c.name}`:`Hide colors of ${c.name}`} title={c.hidden?`Show colors of ${c.name}`:`Hide colors of ${c.name}`} onClick={()=>toggleGroupColors(c.id)}>{c.hidden?<EyeOff size={15}/>:<Palette size={15}/>}</Button>
     <Button variant="ghost" className={`group-icon group-toggle-icon ${c.tagHidden?'is-off':''}`} aria-pressed={!c.tagHidden} aria-label={c.tagHidden?`Show tag of ${c.name}`:`Hide tag of ${c.name}`} title={c.tagHidden?`Show tag of ${c.name}`:`Hide tag of ${c.name}`} onClick={()=>toggleGroupTag(c.id)}><Tag size={15}/></Button>
     <Button variant="ghost" className="group-icon" aria-label={`Edit ${c.name}`} title="Edit" onClick={()=>editGroup(c)}><Pencil size={15}/></Button>
     <Button variant="ghost" className="group-icon" aria-label={`Duplicate ${c.name}`} title="Duplicate" onClick={()=>duplicateGroup(c)}><Copy size={15}/></Button>
     <Button variant="ghost" className="group-icon" aria-label={`Delete ${c.name}`} title="Delete" onClick={()=>setConfirmDelete(c.id)}><Trash2 size={15}/></Button>
    </>}
   </li>)}</ul>:<p className="search-note">Shift-click pieces, or hold Shift and drag a box over the body, then save the selection as a named group with its own colors.</p>}
   {groups.length>0&&<div className="group-toggle"><span>Show labels on the body</span><Switch checked={showLabels} onCheckedChange={checked=>setShowLabels(checked)} aria-label="Show group labels on the body"/></div>}
   <Button className="primary-action" disabled={!state.selected.length} onClick={()=>startDraft({id:null,name:'',parts:state.selected,colors:[nextColor],children:[]})}><Plus size={16}/>New group from selection<span className="group-pending">{state.selected.length}</span></Button>
  </section>}
  {draft&&<section className="search-panel groups-panel glass" aria-label={draft.id?'Edit group':'New group'}>
   <div className="panel-heading"><span>{draft.id?'Edit group':'New group'}</span><Button variant="ghost" className="icon-button" onClick={()=>setDraft(null)} aria-label="Close editor"><X size={18}/></Button></div>
   <label className="group-field"><span>Name</span><Input autoFocus value={draft.name} placeholder="Skull" onChange={e=>setDraft(d=>d&&{...d,name:e.target.value})} onKeyDown={e=>{if(e.key==='Enter')saveDraft();}}/></label>
   <div className="group-field"><span>Color layers<em>{draft.colors.length}/{MAX_LAYERS}</em></span>
    {draft.colors.map((color,i)=><div className="color-row" key={i}><span className="color-picker" style={{background:color}}><input type="color" value={color} aria-label={`Color layer ${i+1}`} onChange={e=>setDraftColor(i,e.target.value)}/></span><HexInput value={color} label={`Color layer ${i+1} hex value`} onChange={hex=>setDraftColor(i,hex)}/><Button variant="ghost" className="group-icon" aria-label={`Remove color layer ${i+1}`} disabled={draft.colors.length<2} onClick={()=>setDraft(d=>d&&{...d,colors:d.colors.filter((_,k)=>k!==i)})}><X size={14}/></Button></div>)}
    <Button variant="ghost" className="group-add" disabled={draft.colors.length>=MAX_LAYERS} onClick={()=>setDraft(d=>d&&{...d,colors:[...d.colors,PALETTE.find(p=>!d.colors.includes(p))??'#000000']})}><Plus size={14}/>Add color layer</Button>
   </div>
   <div className="group-field"><span>Pieces<em>{draft.parts.length}</em></span>
    <div className="group-parts">{draft.parts.map(id=><div className="group-part" key={id}><span>{parts.get(id)?.name??id}</span><Button variant="ghost" className="group-icon" aria-label={`Remove ${parts.get(id)?.name??id}`} onClick={()=>{setDraft(d=>d&&{...d,parts:d.parts.filter(x=>x!==id)});setState(s=>({...s,selected:s.selected.filter(x=>x!==id)}));}}><X size={14}/></Button></div>)}{!draft.parts.length&&<p className="search-note">No pieces yet.</p>}</div>
    <Button variant="ghost" className="group-add" disabled={!pending.length} onClick={()=>setDraft(d=>d&&{...d,parts:[...d.parts,...pending]})}><Plus size={14}/>Add selected pieces{pending.length>0&&` (${pending.length})`}</Button>
    <p className="search-note">Shift-click or Shift-drag on the body to select more pieces.</p>
   </div>
   {includable.length>0&&<div className="group-field"><span>Included groups<em>{draft.children.length}</em></span>
    <div className="group-children">{includable.map(c=><Button variant="ghost" key={c.id} className="group-child" aria-pressed={draft.children.includes(c.id)} onClick={()=>toggleDraftChild(c.id)}><span className="group-swatch" style={{background:stripes(c.colors)}}/><span className="group-label">{c.name}</span><span className="small-number">{piecesOf(c).length}</span>{draft.children.includes(c.id)?<Check size={14}/>:<Plus size={14}/>}</Button>)}</div>
    <p className="search-note">Included groups keep their own colors and also show this group's colors.</p>
   </div>}
   <div className="group-actions"><Button className="primary-action" disabled={!draft.name.trim()||(!draft.parts.length&&!draft.children.length)} onClick={saveDraft}><Check size={16}/>Save group</Button><Button variant="ghost" className="secondary-action" onClick={()=>setDraft(null)}>Cancel</Button></div>
  </section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect <b>·</b> Shift-drag to select many</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:chosen?.colors?.length?stripes(chosen.colors):system?.color}}/><div className="eyebrow">{chosen?.kind==='group'?'GROUP':chosen?.kind==='selection'?'SELECTION':system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen?.kind==='group'?`A group you defined, grouping ${chosen.elements.length.toLocaleString()} modeled pieces.`:chosen?.kind==='selection'?'Shift-click to add or remove pieces, or hold Shift and drag a box to add more. Save them as a named group with its own colors.':chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!chosen.kind&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.kind?'Custom':chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button>{chosen?.kind==='group'?<Button variant="ghost" className="secondary-action group-action" onClick={()=>{const c=groups.find(x=>x.id===chosen.id);if(c)editGroup(c);}}><Pencil size={14}/>Edit group</Button>:<Button variant="ghost" className="secondary-action group-action" onClick={()=>startDraft({id:null,name:'',parts:state.selected,colors:[nextColor],children:[]})}><GroupIcon size={14}/>Group selection</Button>}<Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
